# Generated by Django 5.0.6 on 2024-07-21 01:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_gymuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Workout Name')),
                ('description', models.TextField(help_text='Detailed description of the workout.', verbose_name='Workout Description')),
                ('days_per_week', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Days per Week')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client', verbose_name='Client')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.trainer', verbose_name='Trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Exercise Name')),
                ('sets', models.PositiveIntegerField(verbose_name='Number of Sets')),
                ('reps', models.PositiveIntegerField(verbose_name='Number of Reps')),
                ('tutorial_url', models.URLField(verbose_name='Tutorial URL')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout', verbose_name='Associated Workout')),
            ],
        ),
    ]
