# Generated by Django 5.0.6 on 2024-08-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_gymuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contact',
            new_name='user_contact',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='contact',
            new_name='trainer_contact',
        ),
    ]
